### ISSUE TITLE
custom validation using Regex

### ISSUE THREAD

**Issue by shopper360mst** [colinaut/alpinejs-plugin-simple-validate#10]
Hi is it possible to use custom validation rules using RegEx with this plugin? e.g. i have a different set of validation for Local ID Card number input for example.

**Comment by colinaut** [comment]
Yes. See example below for a field that allows any cheese except American cheese

```
<label for="cheese">Favorite Cheese *</label>
<input
type="text"
id="othercheese"
name="othercheese"
x-validate="!/american/i.test($el.value)"
data-error-msg="any cheese other than American"
/>

```
