### ISSUE TITLE
An error occurs if the name attribute contains [] like "name[last_name]"

### ISSUE THREAD

**Issue by nomin-sasabuchi** [colinaut/alpinejs-plugin-simple-validate#16]
We become indebted to.
It is also in the title, but if the name attribute contains [], an error will occur. Is this the specification?
Also, can this be fixed?

**Comment by colinaut** [comment]
Thanks for the bug report. Fixed! New 1.7.21 release should work for you

What was happening: The [] means something different when using querySelector so it was breaking. I only needed to find by id in my code there so I switched to getElementById and that fixes the issue, and makes the code a bit more concise too which is nice.
