### ISSUE TITLE
type Password not working on first enter hit

### ISSUE THREAD

**Issue by kevinmu17** [colinaut/alpinejs-plugin-simple-validate#21]
When you have a simple login form and you enter your credentials, it fails and console.logs 'password required' When you hit enter again it submits the form. If you remove the required attribute from the password field it works. 

```html
<form x-validate @submit="$validate.submit">
    <input name="name" type="email" required>
    <input type="password" name="password" required>
    <input type="submit" value="Login">
</form>
```

**Comment by colinaut** [comment]
Looking into this. It's definitely an odd one, though I admit I haven't fully testing password fields with the validator. I'll need to dig in to see what is happening.

**Comment by colinaut** [comment]
Ok found the bug! It was an issue with submit validation function that if a user hit return on the last field it didn't blur so didn't validate. It now double checks revalidating the fields on submit. 

New version 1.7.23 fixes the issue
